name: Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  clean-up-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
  checks-and-tests:
    runs-on: [self-hosted, linux]
    env:
      SCCACHE_CACHE_SIZE: "50G"
      CARGO_INCREMENTAL: 0
    needs: clean-up-actions
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2021-06-17
        components: rustfmt
        target: wasm32-unknown-unknown
        default: true
    - name: Build
      run: make build-release
    - name: Install clippy
      run: rustup component add clippy
    - name: Run clippy
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: make test
